name: open_street_map_search_and_pick
description: A flutter place search and location picker plugin that uses Open Street Map.
version: 0.1.1

environment:
  sdk: ">=2.17.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_map: 
  geolocator: 
  http: 
  latlong2: 

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
